### ISSUE TITLE
USER STORY: Update calendar section of site

### ISSUE THREAD

**Issue by domsq** [domsq/My-First-Agile-Project#5]
As a **site admin** I can **update the upcoming run details** so that **users have the most up-to-date information**

### Acceptance Criteria:
- The scheduled runs should be editable via an edit (pencil) icon, only visible to admins
- When the edit icon is clicked, an admin could then update the details for the upcoming runs

### Tasks
- [ ] Update the HTML and CSS to add an edit icon to the calendar section, which is only visible to admins
- [ ] Link the edit icon via JS to the calendar section
- [ ] Create the functionality to allow the edits by an admin
