### ISSUE TITLE
USER STORY: Update picture gallery page

### ISSUE THREAD

**Issue by domsq** [domsq/My-First-Agile-Project#6]
As a **site admin** I can **update the picture gallery page** so that **users can see the latest submissions**

### Acceptance Criteria:
- There should be an edit (pencil) icon visible to admins on the gallery page
- When the edit icon is clicked, this should allow additions to \ removals from the gallery
- The admin should also be able to resize any images if needed for a better layout and fit

### Tasks
- [ ] Add edit icon to gallery page via HTML and CSS additions
- [ ] Link edit icon accordingly using JS
- [ ] Create required functionality using JS \ a framework \ a library as needed
